### ISSUE TITLE
Support user-provided fixed value for dynamic field

### ISSUE THREAD

**Issue by jlandowner** [jlandowner/helm-chartsnap#105]
Option 1

```yaml
dynamicFields:
  - apiVersion: v1
    kind: Secret
    name: cosmo-auth-env
    jsonPath:
      - /data/COOKIE_HASHKEY
      - /data/COOKIE_BLOCKKEY
      - /data/COOKIE_HASHKEY
      - /data/COOKIE_SESSION_NAME
    base64: true
    value: '###DYNAMIC_FIELD###' # Add
```

Option 2

```yaml
dynamicFields:
  - apiVersion: v1
    kind: Secret
    name: cosmo-auth-env
    jsonPath:                         # Support both string and struct array
      - path: /data/COOKIE_HASHKEY    # Change as path property
        value: '###COOKIE_HASHKEY###'
      - path: /data/COOKIE_BLOCKKEY
        value: '###COOKIE_BLOCKKEY###' # This option can set values on each path.
```
