### ISSUE TITLE
[Feature] Warning message with indentation error

### ISSUE THREAD

**Issue by sofia-fernandez-six** [jlandowner/helm-chartsnap#113]
Hi,
I am writing to request a feature enhancement in your chartsnap plugin. Specifically, I would like the system to generate a warning when the indexing of YAML files is incorrect. For example, this example:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
    spec:
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
```

Currently, when there is an issue with the indexing of these files, it can lead to unexpected behavior in our application, which is difficult to debug due to the lack of explicit warnings or error messages.

Implementing this feature would greatly improve our ability to identify and resolve issues more efficiently, thereby improving the overall robustness of our application.

I look forward to your positive response. Because this approach, we could resolve a lot of issues in our debugging.

Thank you for all your help.
Best regards,
Sofía
