### ISSUE TITLE
CLI Options set in `testSpec`

### ISSUE THREAD

**Issue by jlandowner** [jlandowner/helm-chartsnap#13]
Support to run cmd without args such as  `chartsnap -f values.yaml` by using the values file like:

```yaml
testSpec:
  chart: cilium
  additionalArgs: |
    --repo https://helm.cilium.io
    --namespace kube-system
...
```
