### ISSUE TITLE
dynamicFields with / in key

### ISSUE THREAD

**Issue by bendzsak-dpc** [jlandowner/helm-chartsnap#53]
Hi,

I would like to use dynamicFields with kyes which has '/' characters.
Part of the templated yaml:
```
spec:
    template:
        metadata:
            annotations:
                checksum/values: 30da9af9da506b1fc3aa378d47e2d916f1d62e0e30dda84b25e855053233fd33
```

This is the  .chartignore
```
dynamicFields:
  - apiVersion: apps/v1
    kind: Deployment
    name: cosmo-auth-env
    jsonPath:
      - /spec/template/metadata/annotaions/checksum/values
```

I got the following error:
```
chart=. values=test/test.yaml err=failed to replace json path: failed to replace json path: failed to patch JSON6902: replace operation does not apply: doc is missing path: /spec/template/metadata/annotaions/checksum/values: missing value:
```

I tried the following escape segments:
/spec/template/metadata/annotaions/"checksum/values"
/spec/template/metadata/annotaions/'checksum/values'
/spec/template/metadata/annotaions/checksum%2Fvalues

None of the worked for me.

How can I escape the / in the key character?

Thank you for your help!
