### ISSUE TITLE
Unknow warning

### ISSUE THREAD

**Issue by sofiafernandezmoreno** [jlandowner/helm-chartsnap#69]
First of all, thank you so much for this amazing tool.
I'm creating this issue due since several days I'm facing this issue
```
WARN: failed to recognize a resource. snapshot as Unknown:
---
object:
    apiVersion: helm-chartsnap.jlandowner.dev/v1alpha1
    kind: Unknown
    raw: |
        coalesce.go:286: warning: cannot overwrite table with non table for certificate-exporter.hostPathsExporter.securityContext (map[capabilities:map[drop:[ALL]] readOnlyRootFilesystem:true runAsGroup:0 runAsUser:0])
        coalesce.go:286: warning: cannot overwrite table with non table for certificate-exporter.secretsExporter.securityContext (map[capabilities:map[drop:[ALL]] readOnlyRootFilesystem:true runAsGroup:65534 runAsUser:65534])
```
I don't know but maybe could be related with the array section
this is my  values.yaml:
```
certificate-exporter:
  exposePerCertificateErrorMetrics: true
  exposeRelativeMetrics: true
  secretsExporter:
    securityContext: []    
  hostPathsExporter:
    securityContext: []
```
My helm version is 3.14.2
